# Deploy nebula client
- hosts: all
  tasks:
  - name: Create Nebula directory
    file:
      path: /etc/nebula/
      state: directory
    become: yes
  - name: Download nebula binaries
    get_url:
      url: https://github.com/slackhq/nebula/releases/download/v1.2.0/nebula-linux-amd64.tar.gz
      dest: /etc/nebula/
      mode: '0440'
  - name: Unarchive nebula binaries
    unarchive:
      src: /etc/nebula/nebula-linux-amd64.tar.gz
      dest: /etc/nebula
      remote_src: yes
  - name: Copy config file
    template:
      src: config.j2
      dest: /etc/nebula/config.yaml
      mode: 0644
    become: yes
  - name: Generate certificates on ansible host
    local_action: command sh -c 'cd {{ nebula_bin }} && ./nebula-cert sign -name "{{ nebula_client_name }}" -ip "{{ nebula_client_ip }}"'
  - name: Copy ca certificate
    template:
      src: "{{ nebula_bin }}/ca.crt"
      dest: /etc/nebula/ca.crt
      mode: 0644
    become: yes
  - name: Copy client certificate
    template:
      src: "{{ nebula_bin }}/{{ nebula_client_name }}.crt"
      dest: "/etc/nebula/{{ nebula_client_name }}.crt"
      mode: 0644
    become: yes
  - name: Copy client key
    template:
      src: "{{ nebula_bin }}/{{ nebula_client_name }}.key"
      dest: "/etc/nebula/{{ nebula_client_name }}.key"
      mode: 0644
    become: yes
  - name: Copy service file
    template:
      src: nebula.service
      dest: /etc/systemd/system/nebula.service
      mode: 0644
    become: yes
  - name: Start nebula service
    systemd:
      state: restarted
      daemon_reload: yes
      name: nebula
  - name: Enable nebula service at boot
    service:
      name: nebula
      enabled: yes
