# Deploy nebula client
- hosts: all
  tasks:
  - name: Create Nebula directory
    file:
      path: /etc/nebula/
      state: directory
    become: yes
  - name: Download nebula binaries
    get_url:
      url: https://github.com/slackhq/nebula/releases/download/v1.1.0/nebula-linux-amd64.tar.gz
      dest: /etc/nebula/
      mode: '0440'
  - name: Unarchive nebula binaries
    unarchive:
      src: /etc/nebula/nebula-linux-amd64.tar.gz
      dest: /etc/nebula
      remote_src: yes
  - name: Copy config file
    template:
      src: config.j2
      dest: /etc/nebula/config.yml
      mode: 0644
    become: yes
  - name: Copy ca certificate
    template:
      src: ca.crt
      dest: /etc/nebula/ca.crt
      mode: 0644
    become: yes
  - name: Copy client certificate
    template:
      src: {{ nebula_client_name }}.crt
      dest: /etc/nebula/{{ nebula_client_name }}.yml
      mode: 0644
    become: yes
  - name: Copy client key
    template:
      src: {{ nebula_client_name }}.key
      dest: /etc/nebula/{{ nebula_client_name }}.key
      mode: 0644
    become: yes
  - name: Connect to Nebula network
    command: "( ( nohup ./nebula -config /etc/nebula/config.yaml 1>/dev/null 2>&1 ) & )"
    become: yes
