# Installes docker-ce and docker-compose on Debian 10

# Install docker 
- import_playbook: ../../general/playbook_docker.yaml

# Deploy docker-compose
- hosts: all
  tasks:
  - name: Create directory
    file:
      path: /docker
      state: directory
    become: yes
  - name: Copy docker-compose.yml
    template:
      src: docker-compose.j2
      dest: /docker/docker-compose.yml
      mode: 0644
    become: yes
  - name: Create a network
    docker_network:
      name: logging
  - name: Tear down existing services
    docker_compose:
      project_src: /docker 
      state: absent
  - name: Create and start services
    docker_compose:
      project_src: /docker
